const REFRESH_SECONDS=60, MAX_SCAN_RADIUS_KM=25, MAX_LIST_CARDS=500;
try{for(const key of ['location','favorites','filters','species-index','radius-max25-migrated']){const oldKey='wildtrace-'+key,newKey='aminekgogo-'+key;if(localStorage.getItem(newKey)===null&&localStorage.getItem(oldKey)!==null)localStorage.setItem(newKey,localStorage.getItem(oldKey));localStorage.removeItem(oldKey)}}catch(error){console.warn('Could not migrate saved AminekGoGo settings:',error)}
try{if(localStorage.getItem('aminekgogo-radius-max25-migrated')!=='yes'){const oldLocation=JSON.parse(localStorage.getItem('aminekgogo-location')||'null');if(oldLocation&&(oldLocation.radius==null||!Number.isFinite(Number(oldLocation.radius))||Number(oldLocation.radius)<25)){oldLocation.radius=MAX_SCAN_RADIUS_KM;localStorage.setItem('aminekgogo-location',JSON.stringify(oldLocation))}localStorage.setItem('aminekgogo-radius-max25-migrated','yes')}}catch(error){console.warn('Could not update saved scan radius:',error)}
let spawns=[], activeFilter='all', searchTerm='', sortMode='best', favorites=new Set(JSON.parse(localStorage.getItem('aminekgogo-favorites')||'[]')), showFavorites=false, map, markers=[], locationPin=null, refreshTimer, remaining=REFRESH_SECONDS, selectedPlaceLabel='', feedRequest=0;
let filterSettings={ivEnabled:true,cpEnabled:true,iv:90,cp:2500};
try{const savedFilters=JSON.parse(localStorage.getItem('aminekgogo-filters')||'null');if(savedFilters)filterSettings={ivEnabled:savedFilters.ivEnabled!==false,cpEnabled:savedFilters.cpEnabled!==false,iv:Math.min(100,Math.max(80,Number(savedFilters.iv)||90)),cp:Math.min(3000,Math.max(0,Number(savedFilters.cp)||0))}}catch(error){console.warn('Could not load saved filters:',error)}
let globalMode=false, globalHotspots=null, globalDataPromise=null, everythingMode=false, everythingScanning=false, everythingPaused=false, everythingRun=0;
const $=id=>document.getElementById(id);
function normalize(item,index){const lat=Number(item.latitude??item.lat),lon=Number(item.longitude??item.lng??item.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180) return null;const pokemonId=Number(item.pokemon_id??item.pokemonId)||0;let despawnIn=Number(item.despawnIn??item.secondsRemaining)||0,despawnAt=0;if(item.expires_at){const expiry=Date.parse(item.expires_at);if(Number.isFinite(expiry)){despawnAt=expiry;despawnIn=Math.max(0,Math.ceil((expiry-Date.now())/1000))}}if(!despawnAt&&despawnIn>0)despawnAt=Date.now()+despawnIn*1000;return {id:String(item.id??`${item.name||item.pokemonName||pokemonId||'spawn'}-${lat}-${lon}-${index}`),pokemonId,name:String(item.name??item.pokemon_name??item.pokemonName??(pokemonId?`Pokémon #${pokemonId}`:'Unknown Pokémon')),cp:Number(item.cp??item.combatPower)||0,iv:Number(item.iv??item.percent_iv??item.ivPercent??item.individualValue)||0,latitude:lat,longitude:lon,location:String(item.location??item.address??`${lat.toFixed(4)}, ${lon.toFixed(4)}`),despawnIn,despawnAt,emoji:String(item.emoji??'✨'),image:item.image??item.imageUrl??(pokemonId?`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemonId}.png`:null),color:item.color??'#edf4ee'} }
function passesThresholds(s){const matches=[];if(filterSettings.ivEnabled)matches.push(s.iv>=filterSettings.iv);if(filterSettings.cpEnabled)matches.push(s.cp>=filterSettings.cp);return !matches.length||matches.some(Boolean)}
function visibleSpawns(){let arr=spawns.filter(s=>{if(!passesThresholds(s))return false;if(showFavorites&&!favorites.has(s.id))return false;if(searchTerm&&!`${s.name} ${s.location}`.toLowerCase().includes(searchTerm))return false;return true});if(sortMode==='cp')arr.sort((a,b)=>b.cp-a.cp);else if(sortMode==='iv')arr.sort((a,b)=>b.iv-a.iv);else arr.sort((a,b)=>Math.max(b.iv/100,b.cp/3000)-Math.max(a.iv/100,a.cp/3000));return arr}
function mapIcon(s){let kind=s.iv>=filterSettings.iv&&s.cp>=filterSettings.cp?'both':s.iv>=filterSettings.iv?'iv':s.cp>=filterSettings.cp?'cp':'other';let symbol=kind==='iv'?'★':kind==='cp'?'↗':kind==='both'?'✦':'•';return L.divIcon({className:'spawn-pin pin-'+kind,html:`<div class="pin-core"><span>${symbol}</span></div>`,iconSize:[32,38],iconAnchor:[16,34]})}
function clusterMapSpawns(items){
 const zoom=map.getZoom(),cellSize=zoom<=10?72:zoom<=12?64:zoom<=14?56:zoom<=16?48:40,buckets=new Map();
 items.forEach(spawn=>{const point=map.project([spawn.latitude,spawn.longitude],zoom),key=`${Math.floor(point.x/cellSize)}:${Math.floor(point.y/cellSize)}`;if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(spawn)});
 return [...buckets.values()].map(group=>({spawns:group,latitude:group.reduce((sum,s)=>sum+s.latitude,0)/group.length,longitude:group.reduce((sum,s)=>sum+s.longitude,0)/group.length}));
}
function clusterIcon(count){return L.divIcon({className:'spawn-cluster-icon',html:`<span class="spawn-cluster">${count>99?'99+':count}</span>`,iconSize:[42,42],iconAnchor:[21,21]})}
function drawMap(){
 if(!map)return;markers.forEach(m=>map.removeLayer(m));markers=[];const groups=clusterMapSpawns(visibleSpawns());
 groups.forEach(group=>{if(group.spawns.length===1){const s=group.spawns[0],marker=L.marker([s.latitude,s.longitude],{icon:mapIcon(s),bubblingMouseEvents:false}).addTo(map);marker.bindPopup(`<b>${escapeHtml(s.name)}</b><br>CP ${s.cp.toLocaleString()} · ${s.iv}% IV<br>${escapeHtml(s.location)}<br>${s.latitude.toFixed(4)}, ${s.longitude.toFixed(4)}<br><a href="https://www.google.com/maps?q=${s.latitude},${s.longitude}" target="_blank" rel="noreferrer">Open coordinates ↗</a>`);marker.on('click',()=>highlightCard(s.id));markers.push(marker);return}
  const count=group.spawns.length,marker=L.marker([group.latitude,group.longitude],{icon:clusterIcon(count),bubblingMouseEvents:false}).addTo(map);marker.bindPopup(`<b>${count} Pokémon in this area</b><br>Zoom in to separate nearby spawns.`);marker.on('click',()=>{const nextZoom=Math.min(18,map.getZoom()+2);if(nextZoom>map.getZoom())map.setView([group.latitude,group.longitude],nextZoom)});markers.push(marker);
 });
 $('map-subtitle').textContent=showFavorites?'Showing saved sightings':filterSettings.ivEnabled||filterSettings.cpEnabled?'Showing sightings that meet an active minimum':'Showing all sightings';
}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const arr=visibleSpawns();$('spawn-list').innerHTML=arr.slice(0,MAX_LIST_CARDS).map(s=>{const remaining=s.despawnAt?Math.max(0,Math.ceil((s.despawnAt-Date.now())/1000)):0;const urgent=s.despawnAt&&remaining<300;const countdown=s.despawnAt?`${Math.floor(remaining/60)}m ${String(remaining%60).padStart(2,'0')}s`:'—';const art=s.image?`<img src="${escapeHtml(s.image)}" alt="${escapeHtml(s.name)}" loading="lazy">`:escapeHtml(s.emoji);return `<article class="spawn-card" data-id="${escapeHtml(s.id)}"><div class="pokemon-art" style="--art-bg:${escapeHtml(s.color)}">${art}${s.iv>=filterSettings.iv?'<span class="tiny-star">★</span>':''}</div><div class="spawn-info"><div class="spawn-title"><strong>${escapeHtml(s.name)}</strong><span class="gender">♀ ♂</span></div><div class="spawn-place">⌖ ${escapeHtml(s.location)}</div><div class="spawn-metrics"><span class="metric cp">CP <strong>${s.cp.toLocaleString()}</strong></span><span class="metric iv">★ <strong>${s.iv}%</strong> IV</span></div></div><div class="spawn-end"><span class="timer ${urgent?'urgent':''}" data-expires-at="${s.despawnAt||''}">◷ ${countdown}</span><div class="card-actions"><a class="coord-link" href="https://www.google.com/maps?q=${s.latitude},${s.longitude}" target="_blank" rel="noreferrer">${s.latitude.toFixed(4)}, ${s.longitude.toFixed(4)}</a><button class="${favorites.has(s.id)?'saved':''}" data-favorite="${escapeHtml(s.id)}" aria-label="Save ${escapeHtml(s.name)}" title="Save Pokémon">${favorites.has(s.id)?'♥':'♡'}</button></div></div></article>`}).join('');$('spawn-list').querySelectorAll('.spawn-card').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('a,button'))return;const s=spawns.find(x=>x.id===el.dataset.id);if(s){map?.setView([s.latitude,s.longitude],15);markers.find(m=>String(m.getLatLng().lat)===String(s.latitude))?.openPopup()}}));$('spawn-list').querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.favorite)));$('empty-state').hidden=arr.length!==0;$('showing-count').textContent=Math.min(arr.length,MAX_LIST_CARDS).toLocaleString();$('all-count').textContent=spawns.length.toLocaleString();$('total-count').textContent=spawns.length;$('high-iv-count').textContent=spawns.filter(s=>s.iv>=filterSettings.iv).length;$('high-cp-count').textContent=spawns.filter(s=>s.cp>=filterSettings.cp).length;drawMap()}
function highlightCard(id){document.querySelector(`[data-id="${CSS.escape(id)}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest'})}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('aminekgogo-favorites',JSON.stringify([...favorites]));render()}
function cpThresholdLabel(value){return `${Number(value).toLocaleString()}${Number(value)>=3000?'+':''}`}
function syncFilterControls(){
 $('filter-iv').value=filterSettings.iv;$('filter-cp').value=filterSettings.cp;$('filter-iv-enabled').checked=filterSettings.ivEnabled;$('filter-cp-enabled').checked=filterSettings.cpEnabled;
 $('filter-iv-value').textContent=`${filterSettings.iv}%`;$('filter-cp-value').textContent=cpThresholdLabel(filterSettings.cp);
 const activeCount=Number(filterSettings.ivEnabled)+Number(filterSettings.cpEnabled);$('filter-active-count').textContent=activeCount?`${activeCount} active`:'Off';$('filter-toggle').setAttribute('aria-expanded',String(!$('filter-panel').hidden));
 $('high-iv-label').textContent=`IV ≥ ${filterSettings.iv}%`;$('high-cp-label').textContent=`CP ≥ ${cpThresholdLabel(filterSettings.cp)}`;
}
function saveFilterSettings(){localStorage.setItem('aminekgogo-filters',JSON.stringify(filterSettings));syncFilterControls();render()}
function closeFilterPanel(){ $('filter-panel').hidden=true;syncFilterControls() }
function openFilterPanel(){ $('filter-panel').hidden=false;syncFilterControls() }
syncFilterControls();
$('filter-toggle').addEventListener('click',()=>{$('filter-panel').hidden?openFilterPanel():closeFilterPanel()});
$('filter-close').addEventListener('click',closeFilterPanel);
$('filter-iv').addEventListener('input',e=>{filterSettings.iv=Number(e.target.value);saveFilterSettings()});
$('filter-cp').addEventListener('input',e=>{filterSettings.cp=Number(e.target.value);saveFilterSettings()});
$('filter-iv-enabled').addEventListener('change',e=>{filterSettings.ivEnabled=e.target.checked;saveFilterSettings()});
$('filter-cp-enabled').addEventListener('change',e=>{filterSettings.cpEnabled=e.target.checked;saveFilterSettings()});
$('filter-reset').addEventListener('click',()=>{filterSettings={ivEnabled:true,cpEnabled:true,iv:90,cp:2500};saveFilterSettings()});
document.addEventListener('click',e=>{if(!$('filter-panel').hidden&&!e.target.closest('.filter-control'))closeFilterPanel()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('filter-panel').hidden)closeFilterPanel()});
function tickDespawnTimers(){document.querySelectorAll('.timer[data-expires-at]').forEach(timer=>{const expiresAt=Number(timer.dataset.expiresAt);if(!expiresAt)return;const remaining=Math.max(0,Math.ceil((expiresAt-Date.now())/1000));timer.textContent=`◷ ${Math.floor(remaining/60)}m ${String(remaining%60).padStart(2,'0')}s`;timer.classList.toggle('urgent',remaining<300)})}
function startRefresh(){clearInterval(refreshTimer);if(globalMode)return;if(everythingMode){if(everythingScanning||everythingPaused){$('refresh-counter').textContent=everythingScanning?'scanning':'paused';refreshTimer=setInterval(tickDespawnTimers,1000);return}remaining=REFRESH_SECONDS;$('refresh-counter').textContent=`${remaining}s`;refreshTimer=setInterval(()=>{tickDespawnTimers();remaining--;if(remaining<=0){scanEverything();return}$('refresh-counter').textContent=`${remaining}s`},1000);return}if(!localStorage.getItem('aminekgogo-location')){$('refresh-counter').textContent='—';return}remaining=REFRESH_SECONDS;$('refresh-counter').textContent=`${remaining}s`;refreshTimer=setInterval(()=>{tickDespawnTimers();remaining--;if(remaining<=0){remaining=REFRESH_SECONDS;loadFeed()}$('refresh-counter').textContent=`${remaining}s`},1000)}
function isLocalHost(){return ['localhost','127.0.0.1'].includes(window.location.hostname)}
function apiUrl(path){
 if(isLocalHost())return path;
 const base=String(window.AMINEKGOGO_API_BASE||'').replace(/\/$/,'');
 if(!base)throw new Error('Set window.AMINEKGOGO_API_BASE in config.js to your Cloudflare Worker URL.');
 return `${base}${path}`;
}
async function addPokemonNames(items){let names=JSON.parse(localStorage.getItem('aminekgogo-species-index')||'{}');if(!Object.keys(names).length){try{const response=await fetch('https://pokeapi.co/api/v2/pokemon-species?limit=2000',{headers:{Accept:'application/json'}});if(response.ok){const data=await response.json();for(const species of data.results||[]){const match=species.url.match(/\/(\d+)\/?$/);if(match)names[match[1]]=species.name.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}localStorage.setItem('aminekgogo-species-index',JSON.stringify(names))}}catch(error){console.warn('Could not load Pokémon names:',error)}}return items.map(s=>s.pokemonId&&names[s.pokemonId]?{...s,name:names[s.pokemonId]}:s)}
function setEmptyState(title='No sightings found',text='Try changing your filters or search.',jump=null){const box=$('empty-state'),button=$('coverage-jump');box.querySelector('strong').textContent=title;box.querySelector('p').textContent=text;button.hidden=!jump;button.onclick=null;if(jump){button.textContent=`Go to ${hotspotName(jump)}`;button.onclick=()=>loadHotspot(jump)}}
function showCoverageGap(location,requestId){
 setEmptyState('No Pokémon coverage here',"The data provider doesn't scan this area yet.");
 loadHotspotIndex().then(items=>{if(requestId!==feedRequest||spawns.length||globalMode||everythingMode)return;const near=nearestHotspot(items,Number(location.lat),Number(location.lon));if(!near)return;
  if(near.km<MAX_SCAN_RADIUS_KM){setEmptyState('No sightings right now','This area is normally covered. Try refreshing in a few minutes.');return}
  const place=[hotspotName(near.hotspot),near.hotspot.country_code].filter(Boolean).join(', ');setEmptyState('No Pokémon coverage here',`The data provider doesn't scan this area yet. Nearest covered area: ${place} (${Math.round(near.km).toLocaleString()} km).`,near.hotspot);$('feed-detail').textContent=`No coverage near ${location.label||'this location'}`;
 }).catch(error=>console.warn('Could not find the nearest covered area:',error));
}
async function loadFeed(){if(globalMode||everythingMode)return;const location=JSON.parse(localStorage.getItem('aminekgogo-location')||'null');if(!location){spawns=[];$('feed-label').textContent='Choose a scan location';$('feed-detail').textContent='Search for a place or click the map to scan.';$('updated-label').textContent='No scan location selected';$('list-footer-note').textContent='Select a place to start the scan';$('map-subtitle').textContent='Search for a place to scan';setEmptyState('No sightings found','Search for a place above the map or click the map to set a scan pin.');render();return}const requestId=++feedRequest,params=new URLSearchParams({lat:String(location.lat),lon:String(location.lon),radius_km:String(location.radius||MAX_SCAN_RADIUS_KM),layers:'spawns',limit:'800'});$('feed-label').textContent='Updating live feed';$('feed-detail').textContent=`Scanning ${location.radius||MAX_SCAN_RADIUS_KM} km around ${Number(location.lat).toFixed(4)}, ${Number(location.lon).toFixed(4)}`;try{const response=await fetch(`${apiUrl('/api/nearby')}?${params}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error(`Live feed returned HTTP ${response.status}`);const data=await response.json();if(requestId!==feedRequest)return;if(!data||!Array.isArray(data.spawns))throw new Error('The live feed returned an unexpected response.');spawns=data.spawns.map(normalize).filter(Boolean);$('feed-label').textContent='Live community feed';$('feed-detail').textContent=spawns.length?`${spawns.length} nearby spawns · feed refreshes every minute`:`No provider results near ${location.label||'this location'} in a ${location.radius||MAX_SCAN_RADIUS_KM} km scan.`;$('updated-label').textContent=`Updated ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;if(map)map.setView([location.lat,location.lon],Math.min(15,Math.max(11,Math.round(15-Math.log2(location.radius||2)))));if(spawns.length)setEmptyState();else showCoverageGap(location,requestId);render();addPokemonNames(spawns).then(named=>{if(requestId===feedRequest){spawns=named;render()}}).catch(error=>console.warn('Could not load Pokémon names:',error))}catch(error){if(requestId!==feedRequest)return;$('feed-label').textContent='Live feed unavailable';$('feed-detail').textContent=error.message;$('updated-label').textContent='Could not refresh live feed';console.error('AminekGoGo live feed error:',error)}}
document.querySelectorAll('.filter-chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-chip').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeFilter=b.dataset.filter;render()}));$('search').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();render()});$('sort-button').addEventListener('click',()=>{sortMode=sortMode==='best'?'cp':sortMode==='cp'?'iv':'best';$('sort-button').querySelector('span').textContent=sortMode==='best'?'Best match':sortMode==='cp'?'Highest CP':'Highest IV';render()});$('refresh-now').addEventListener('click',()=>{if(everythingMode){scanEverything();return}loadFeed();startRefresh()});$('locate-button').addEventListener('click',()=>{if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds().pad(.16),{maxZoom:14})});$('today-date').textContent=new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date());const savedLocation=JSON.parse(localStorage.getItem('aminekgogo-location')||'null');selectedPlaceLabel=savedLocation?.label||'';if(savedLocation)$('region-label').textContent=savedLocation.label||`${Number(savedLocation.lat).toFixed(3)}, ${Number(savedLocation.lon).toFixed(3)}`;map=L.map('map',{zoomControl:false,scrollWheelZoom:true}).setView(savedLocation?[savedLocation.lat,savedLocation.lon]:[52.2297,21.0122],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);map.on('zoomend',()=>{if(!globalMode)drawMap()});loadFeed();startRefresh();

const renderNearby=render;
render=function(){if(globalMode){renderHotspots();return}const scanButton=$('scan-everything');if(everythingMode){scanButton.hidden=!everythingScanning;scanButton.textContent='Stop scan';$('status-mode').textContent='WORLD';$('list-heading').textContent='Everything found';$('list-footer-note').innerHTML=everythingPaused?'Every hotspot · Auto-refresh paused':'Every hotspot · Auto-refresh <b>●</b>';$('search').placeholder='Search Pokémon or location...';$('map-note').textContent='Click map to set a scan pin';document.querySelector('.map-legend').hidden=false;syncFilterControls();renderNearby();return}scanButton.hidden=true;$('status-mode').textContent='LIVE';$('list-heading').textContent='Nearby sightings';$('list-footer-note').innerHTML='Auto-refresh <b>●</b>';$('search').placeholder='Search Pokémon or location...';$('map-note').textContent='Click map to set a scan pin';document.querySelector('.map-legend').hidden=false;syncFilterControls();renderNearby()};
function hotspotName(h){return h.city||h.region||h.country_name||h.country_code||'Known hotspot'}
function hotspotContext(h){return [h.region,h.country_name&&h.country_name!==h.country_code?h.country_name:null,h.country_code].filter((v,i,a)=>v&&v!==hotspotName(h)&&a.indexOf(v)===i).join(', ')}
function activateNav(id){document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.id===id))}
function loadHotspotIndex(){
 if(!globalDataPromise)globalDataPromise=fetch('global-hotspots.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Hotspot list returned HTTP ${r.status}`);return r.json()}).then(d=>(d.countries||[]).flatMap(c=>(c.spots||[]).map(h=>({...h,country_code:h.country_code||c.country_code,country_name:c.country_name||c.country_code})))).then(items=>items.filter(h=>Number.isFinite(Number(h.lat))&&Number.isFinite(Number(h.lon))&&Math.abs(Number(h.lat))<=90&&Math.abs(Number(h.lon))<=180)).catch(error=>{globalDataPromise=null;throw error});
 return globalDataPromise;
}
function distanceKm(lat1,lon1,lat2,lon2){const r=Math.PI/180,dLat=(lat2-lat1)*r,dLon=(lon2-lon1)*r,a=Math.sin(dLat/2)**2+Math.cos(lat1*r)*Math.cos(lat2*r)*Math.sin(dLon/2)**2;return 12742*Math.asin(Math.sqrt(a))}
function nearestHotspot(items,lat,lon){let best=null;for(const h of items){const km=distanceKm(lat,lon,Number(h.lat),Number(h.lon));if(!best||km<best.km)best={hotspot:h,km}}return best}
function leaveEverything(){if(!everythingMode&&!everythingScanning)return;everythingRun++;everythingMode=false;everythingScanning=false;everythingPaused=false}
async function showWorldHotspots(){
 leaveEverything();globalMode=true;showFavorites=false;clearInterval(refreshTimer);feedRequest++;activateNav('world-nav');document.querySelector('.map-legend').hidden=true;
 document.querySelector('.filter-control').hidden=true;$('sort-button').hidden=true;$('search').placeholder='Search city, region, or country...';$('status-mode').textContent='WORLD';$('refresh-counter').textContent='';$('feed-label').textContent='World hotspot index';$('feed-detail').textContent='Select a hotspot to load its live spawns';
 $('high-iv-label').textContent='HOTSPOTS';$('high-cp-label').textContent='COUNTRIES';$('list-heading').textContent='Known spawn hotspots';$('list-footer-note').textContent='Select a hotspot for live Pokémon';$('map-subtitle').textContent='Known spawn areas worldwide';$('map-note').textContent='Click map to pin · click a hotspot for live spawns';setEmptyState('No hotspots found','Try another city or country.');
 $('feed-label').textContent='Loading hotspot index';try{globalHotspots=await loadHotspotIndex();if(!globalMode)return;$('feed-label').textContent='World hotspot index';$('feed-detail').textContent=`${globalHotspots.length} known areas · choose one for live spawns`;$('updated-label').textContent='Curated community coverage · not a live global scan';$('hotspot-count').textContent=globalHotspots.length;$('high-iv-count').textContent=globalHotspots.length;$('high-cp-count').textContent=new Set(globalHotspots.map(h=>h.country_code)).size;render()}catch(error){if(!globalMode)return;$('feed-label').textContent='Hotspot index unavailable';$('feed-detail').textContent=error.message;$('updated-label').textContent='Could not load hotspot index';$('spawn-list').innerHTML='';$('empty-state').hidden=false;setEmptyState('Hotspot list unavailable','Check your connection and try World Hotspots again.')}
}
function renderHotspots(){
 if(!globalHotspots)return;const scanButton=$('scan-everything');scanButton.hidden=false;scanButton.textContent='Show everything';const q=$('search').value.trim().toLowerCase();const items=globalHotspots.map((h,index)=>({...h,index})).filter(h=>!q||`${hotspotName(h)} ${hotspotContext(h)}`.toLowerCase().includes(q));
 $('spawn-list').innerHTML=items.map(h=>`<button type="button" class="hotspot-card" data-hotspot="${h.index}"><span class="hotspot-symbol">◎</span><span class="hotspot-info"><strong>${escapeHtml(hotspotName(h))}</strong><small>${escapeHtml(hotspotContext(h)||h.country_code||'Known spawn area')}</small></span><span class="hotspot-action">View live ↗</span></button>`).join('');
 $('spawn-list').querySelectorAll('[data-hotspot]').forEach(button=>button.addEventListener('click',()=>loadHotspot(globalHotspots[Number(button.dataset.hotspot)])));
 $('empty-state').hidden=items.length!==0;$('showing-count').textContent=items.length;$('all-count').textContent=globalHotspots.length;$('total-count').textContent=globalHotspots.length;drawHotspotMap(items);
}
function drawHotspotMap(items){
 if(!map||!globalHotspots)return;markers.forEach(m=>map.removeLayer(m));markers=[];
 const plotted=items;plotted.forEach(h=>{const marker=L.circleMarker([h.lat,h.lon],{radius:6,weight:2,color:'#f5d6d7',fillColor:'#b44045',fillOpacity:.9,bubblingMouseEvents:false}).addTo(map);marker.bindPopup(`<b>${escapeHtml(hotspotName(h))}</b><br>${escapeHtml(hotspotContext(h)||'Known spawn hotspot')}<br><small>Select this area to load live spawns.</small>`);marker.on('click',()=>loadHotspot(h));markers.push(marker)});
 if(plotted.length){const bounds=L.latLngBounds(plotted.map(h=>[h.lat,h.lon]));map.fitBounds(bounds,{padding:[24,24],maxZoom:3})}
}
function loadHotspot(h){
 leaveEverything();globalMode=false;document.querySelector('.filter-control').hidden=false;$('sort-button').hidden=false;activateNav('live-nav');showFavorites=false;activeFilter='all';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('selected',b.dataset.filter==='all'));
 const label=[hotspotName(h),hotspotContext(h)].filter(Boolean).join(', ');const old=JSON.parse(localStorage.getItem('aminekgogo-location')||'{}');const location={lat:Number(h.lat),lon:Number(h.lon),radius:old.radius||MAX_SCAN_RADIUS_KM,label};localStorage.setItem('aminekgogo-location',JSON.stringify(location));selectedPlaceLabel=label;$('region-label').textContent=label;$('search').value='';searchTerm='';map.setView([location.lat,location.lon],13);placeLocationPin(location.lat,location.lon,label);$('feed-label').textContent='Connecting to live feed';$('feed-detail').textContent=`Loading spawns near ${label}`;loadFeed();startRefresh();
}
$('world-nav').addEventListener('click',showWorldHotspots);
function scanCenters(items){const centers=[];[...items].sort((a,b)=>(Number(b.point_count)||0)-(Number(a.point_count)||0)).forEach(h=>{if(!centers.some(c=>distanceKm(Number(c.lat),Number(c.lon),Number(h.lat),Number(h.lon))<MAX_SCAN_RADIUS_KM-5))centers.push(h)});return centers}
async function scanEverything(){
 const run=++everythingRun;feedRequest++;clearInterval(refreshTimer);
 let items;try{items=await loadHotspotIndex()}catch(error){if(run!==everythingRun)return;$('feed-label').textContent='Hotspot index unavailable';$('feed-detail').textContent=error.message;if(everythingMode)startRefresh();return}
 if(run!==everythingRun)return;
 const refreshing=everythingMode&&spawns.length>0;
 globalMode=false;everythingMode=true;everythingScanning=true;everythingPaused=false;showFavorites=false;document.querySelector('.filter-control').hidden=false;$('sort-button').hidden=false;activateNav('world-nav');
 if(!refreshing){$('search').value='';searchTerm=''}
 const centers=scanCenters(items),found=new Map(),endpoint=apiUrl('/api/nearby');let next=0,done=0,failed=0,lastDraw=0;
 const progress=()=>{const text=`${refreshing?'Refreshing · ':''}Scanned ${done} of ${centers.length} areas · ${found.size.toLocaleString()} Pokémon found${failed?` · ${failed} failed`:''}`;$('updated-label').textContent=text;$('feed-detail').textContent=text};
 $('feed-label').textContent=refreshing?'Refreshing every hotspot':'Scanning every hotspot';progress();startRefresh();
 if(!refreshing){spawns=[];setEmptyState('Scanning hotspots…','Pokémon appear here as each area finishes.')}
 render();
 async function worker(){
  while(next<centers.length&&run===everythingRun){
   const h=centers[next++],label=[hotspotName(h),h.country_code].filter(Boolean).join(', ');
   try{
    const params=new URLSearchParams({lat:String(h.lat),lon:String(h.lon),radius_km:String(MAX_SCAN_RADIUS_KM),layers:'spawns',limit:'800'});
    const response=await fetch(`${endpoint}?${params}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error(`Live feed returned HTTP ${response.status}`);
    const data=await response.json(),batch=await addPokemonNames((Array.isArray(data?.spawns)?data.spawns:[]).map((item,i)=>normalize({...item,location:item.location??`Near ${label}`},i)).filter(Boolean));
    if(run!==everythingRun)return;batch.forEach(s=>{if(!found.has(s.id))found.set(s.id,s)});
   }catch(error){failed++;console.warn(`Could not scan ${label}:`,error)}
   if(run!==everythingRun)return;
   done++;progress();if(!refreshing){spawns=[...found.values()];if(Date.now()-lastDraw>700){lastDraw=Date.now();render()}}
  }
 }
 await addPokemonNames([]);if(run!==everythingRun)return;
 await Promise.all(Array.from({length:4},worker));
 if(run!==everythingRun)return;
 everythingScanning=false;spawns=[...found.values()];$('feed-label').textContent='Everything found';
 const summary=`Updated ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · ${centers.length} areas · ${spawns.length.toLocaleString()} Pokémon${failed?` · ${failed} failed`:''}`;$('updated-label').textContent=summary;$('feed-detail').textContent=`${summary} · refreshes every minute`;
 setEmptyState(spawns.length?'No sightings found':'Nothing found',spawns.length?'Try changing your filters or search.':'No hotspot returned any Pokémon. Try again in a few minutes.');render();startRefresh();
}
function stopEverythingScan(){everythingRun++;everythingScanning=false;everythingPaused=true;$('feed-label').textContent='Scan stopped';$('updated-label').textContent=`Scan stopped · showing ${spawns.length.toLocaleString()} Pokémon`;$('feed-detail').textContent='Auto-refresh paused · press ↻ to scan again';setEmptyState();render();startRefresh()}
$('scan-everything').addEventListener('click',()=>{if(everythingScanning)stopEverythingScan();else scanEverything()});

$('live-nav').addEventListener('click',()=>{leaveEverything();if(globalMode){globalMode=false;document.querySelector('.filter-control').hidden=false;$('sort-button').hidden=false}activateNav('live-nav');showFavorites=false;loadFeed();startRefresh()});
function placeLocationPin(lat,lon,label){if(!map)return;const icon=L.divIcon({className:'location-pin',html:'<span>●</span>',iconSize:[26,26],iconAnchor:[13,13]});if(locationPin)map.removeLayer(locationPin);locationPin=L.marker([lat,lon],{icon,zIndexOffset:1000,keyboard:true,bubblingMouseEvents:false,title:`Scan location: ${label}`}).addTo(map);locationPin.bindTooltip(`${escapeHtml(label)}<br>${Number(lat).toFixed(4)}, ${Number(lon).toFixed(4)}`,{direction:'top',offset:[0,-12],opacity:1})}
function selectMapLocation(lat,lon,placeLabel){
 leaveEverything();clearTimeout(mapPlaceTimer);mapPlaceRequest++;const old=JSON.parse(localStorage.getItem('aminekgogo-location')||'{}'),label=placeLabel||`Pinned ${lat.toFixed(4)}, ${lon.toFixed(4)}`,location={lat,lon,radius:old.radius||MAX_SCAN_RADIUS_KM,label};
 globalMode=false;showFavorites=false;document.querySelector('.filter-control').hidden=false;$('sort-button').hidden=false;activateNav('live-nav');activeFilter='all';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('selected',b.dataset.filter==='all'));$('search').value='';searchTerm='';$('region-label').textContent=label;$('status-mode').textContent='LIVE';$('refresh-counter').textContent='60s';$('high-iv-label').textContent='HIGH IV';$('high-cp-label').textContent='HIGH CP';document.querySelector('.map-legend').hidden=false;$('map-note').textContent='Click map to set a scan pin';$('list-heading').textContent='Nearby sightings';$('list-footer-note').innerHTML='Auto-refresh <b>●</b>';$('updated-label').textContent='Loading live spawns for pinned location';
 localStorage.setItem('aminekgogo-location',JSON.stringify(location));selectedPlaceLabel=label;$('map-place-query').value=label;$('map-place-results').hidden=true;$('map-place-clear').hidden=false;spawns=[];map.setView([lat,lon],placeLabel?13:Math.max(13,map.getZoom()));placeLocationPin(lat,lon,label);render();$('feed-label').textContent='Updating live feed';$('feed-detail').textContent=`Scanning near pinned location · ${location.radius} km radius`;loadFeed();startRefresh();
}
if(savedLocation)placeLocationPin(Number(savedLocation.lat),Number(savedLocation.lon),savedLocation.label||'Pinned scan location');
map.on('click',event=>selectMapLocation(event.latlng.lat,event.latlng.lng));

let mapPlaceTimer=null,mapPlaceRequest=0,mapPlaceFeatures=[];
function parseCoordinateQuery(query){const match=query.match(/^\s*\(?\s*([+-]?\d{1,2}(?:\.\d+)?)\s*[,;\s]\s*([+-]?\d{1,3}(?:\.\d+)?)\s*\)?\s*$/);if(!match)return null;const lat=Number(match[1]),lon=Number(match[2]);return Math.abs(lat)<=90&&Math.abs(lon)<=180?{lat,lon}:null}
async function searchMapPlaces(query){
 const results=$('map-place-results'),requestId=++mapPlaceRequest;
 if(query.length<2){results.hidden=true;results.replaceChildren();mapPlaceFeatures=[];return}
 const coordinates=parseCoordinateQuery(query);
 if(coordinates){mapPlaceFeatures=[];results.hidden=false;results.innerHTML=`<button class="map-place-result" type="button" role="option" data-coordinate-pair><strong>Use these coordinates</strong><small>${coordinates.lat.toFixed(6)}, ${coordinates.lon.toFixed(6)} · scan this location</small></button>`;results.querySelector('[data-coordinate-pair]').addEventListener('click',()=>selectMapLocation(coordinates.lat,coordinates.lon,`${coordinates.lat.toFixed(6)}, ${coordinates.lon.toFixed(6)}`));return}
 results.hidden=false;results.innerHTML='<div class="map-place-message">Searching places…</div>';
 try{
  const params=new URLSearchParams({q:query});
  const response=await fetch(`${apiUrl('/api/geocode')}?${params}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Place search returned HTTP ${response.status}`);
  const data=await response.json();if(requestId!==mapPlaceRequest)return;mapPlaceFeatures=Array.isArray(data.features)?data.features:[];
  if(!mapPlaceFeatures.length){results.innerHTML='<div class="map-place-message">No matching places found.</div>';return}
  results.innerHTML=mapPlaceFeatures.map((feature,index)=>{const p=feature.properties||{},name=p.name||p.city||p.street||'Unnamed place',context=[p.street,p.district,p.city,p.state,p.country].filter((value,i,array)=>value&&value!==name&&array.indexOf(value)===i).join(', ');return `<button class="map-place-result" type="button" role="option" data-place-index="${index}"><strong>${escapeHtml(name)}</strong><small>${escapeHtml(context||'OpenStreetMap place')}</small></button>`}).join('');
  results.querySelectorAll('[data-place-index]').forEach(button=>button.addEventListener('click',()=>{const feature=mapPlaceFeatures[Number(button.dataset.placeIndex)],coords=feature?.geometry?.coordinates||[],p=feature?.properties||{};if(coords.length<2)return;const lat=Number(coords[1]),lon=Number(coords[0]),name=p.name||p.city||p.street||'Selected place',label=[name,p.city,p.state,p.country].filter((value,i,array)=>value&&array.indexOf(value)===i).join(', ');selectMapLocation(lat,lon,label)}));
 }catch(error){if(requestId!==mapPlaceRequest)return;results.innerHTML=`<div class="map-place-message">${escapeHtml(error.message)}</div>`}
}
$('map-place-query').value=savedLocation?.label||'';
$('map-place-query').addEventListener('input',event=>{const query=event.target.value.trim();$('map-place-clear').hidden=!query;clearTimeout(mapPlaceTimer);mapPlaceTimer=setTimeout(()=>searchMapPlaces(query),500)});
 $('map-place-query').addEventListener('keydown',event=>{if(event.key==='Enter'){const coordinates=parseCoordinateQuery(event.currentTarget.value);if(coordinates){event.preventDefault();selectMapLocation(coordinates.lat,coordinates.lon,`${coordinates.lat.toFixed(6)}, ${coordinates.lon.toFixed(6)}`);return}if(!$('map-place-results').hidden){const first=$('map-place-results').querySelector('[data-place-index]');if(first){event.preventDefault();first.click()}}}if(event.key==='Escape')$('map-place-results').hidden=true});
$('map-place-clear').addEventListener('click',()=>{$('map-place-query').value='';$('map-place-clear').hidden=true;$('map-place-results').hidden=true;$('map-place-query').focus();mapPlaceRequest++;clearTimeout(mapPlaceTimer)});

